### ISSUE TITLE
(Feature Request) Time before you can pull the apparatus 

### ISSUE THREAD

**Issue by slayer6409** [LoafOrc/FacilityMeltdown#29]
If possible would it be possible to add a config value to where people can't pull the apparatus until a certain time, or after a certain amount of time has passed?

**Comment by LoafOrc** [comment]
ive thought about the problem of griefers before and thought about this. the problem is that it's too restrictive, sometimes you just wanna rush for the apparatus. instead i'll probably be bringing in a system where based on the percentage of people nearby to the apparatus it takes a different amount of time to pull out and an optional config to require at least x people to pull it out.
